added book logic
Oleksii-Melashchenko/Shop pull request #1
Opened 2024-11-22 00:27 UTC by Oleksii-Melashchenko

2024-11-22 07:55 UTC, liliia-ponomarenko requested changes
Good job! Let’s  fix a few mistakes ;)

2024-11-22 07:55 UTC, liliia-ponomarenko commented on pom.xml
> +</project>
add one empty line at the end of the file

2024-11-22 07:55 UTC, liliia-ponomarenko commented on src/main/java/com/clozex/shop/ShopApplication.java
> +        this.bookService = bookService;
Let’s  use RequiredArgsConstructor

2024-11-22 07:55 UTC, liliia-ponomarenko commented on src/main/java/com/clozex/shop/service/impl/BookServiceImpl.java
> +        this.bookRepository = bookRepository;
the same

2024-11-22 07:55 UTC, liliia-ponomarenko commented on src/main/java/com/clozex/shop/service/impl/BookServiceImpl.java
> +
```suggestion
```

2024-11-23 11:12 UTC, Elena-Bruyako requested changes
see comments

2024-11-23 11:12 UTC, Elena-Bruyako commented on src/main/java/com/clozex/shop/model/Book.java
> +@Data
don't use `@Data` for entities
```suggestion
@Getter
@Setter
```

2024-11-23 11:12 UTC, Elena-Bruyako commented on src/main/java/com/clozex/shop/repository/impl/BookRepositoryImpl.java
> +@Repository
```suggestion
@Repository
@RequiredArgsConstructor
```

2024-11-23 11:12 UTC, Elena-Bruyako commented on src/main/java/com/clozex/shop/repository/impl/BookRepositoryImpl.java
> +    }
```suggestion
    private final SessionFactory sessionFactory;
```

2024-11-23 11:12 UTC, Elena-Bruyako commented on src/main/java/com/clozex/shop/repository/impl/BookRepositoryImpl.java
> +            throw new RuntimeException("Can`t save book" + book, e);
```suggestion
            throw new DataProcessingException("Can`t save book" + book, e);
```

2024-11-23 11:12 UTC, Elena-Bruyako commented on src/main/java/com/clozex/shop/repository/impl/BookRepositoryImpl.java
> +        }
add catch block

2024-11-23 15:48 UTC, Elena-Bruyako approved these changes

2024-11-23 16:33 UTC, merged