added JWT auth, and some refactor
Oleksii-Melashchenko/Shop pull request #10
Opened 2024-12-03 20:04 UTC by Oleksii-Melashchenko

2024-12-04 07:36 UTC, liliia-ponomarenko requested changes
Good job! Let’s  fix a few mistakes ;)

2024-12-04 07:36 UTC, liliia-ponomarenko commented on src/main/java/com/clozex/shop/controller/BookController.java
> +    @PreAuthorize("hasAnyRole('USER', 'ADMIN')")
every user has a USER role. so you can validate only the USER role

2024-12-04 07:36 UTC, liliia-ponomarenko commented on src/main/java/com/clozex/shop/repository/role/RoleRepository.java
> +    Set<Role> findByName(RoleName roleName);
Why Set?

2024-12-04 07:36 UTC, liliia-ponomarenko commented on src/main/java/com/clozex/shop/service/impl/UserServiceImpl.java
> +        user.setRoles(roleRepository.findByName(RoleName.ROLE_USER));
return the previous realization

2024-12-06 12:22 UTC, Elena-Bruyako requested changes
see comments

2024-12-06 12:22 UTC, Elena-Bruyako commented on pom.xml
> +            <version>0.12.6</version>
create property for version

2024-12-06 12:22 UTC, Elena-Bruyako commented on src/main/java/com/clozex/shop/config/OpenApiConfig.java
> +        .components(new Components().addSecuritySchemes("BearerAuth",
сheck tabulation
Create constant for all strings

2024-12-06 12:22 UTC, Elena-Bruyako commented on src/main/java/com/clozex/shop/config/SecurityConfig.java
> +    AuthenticationManager authenticationManager(
```suggestion
    public AuthenticationManager authenticationManager(
```

2024-12-06 12:22 UTC, Elena-Bruyako commented on src/main/java/com/clozex/shop/config/SecurityConfig.java
> +    public RoleHierarchy roleHierarchy() {
why do you need this?

2024-12-07 09:48 UTC, Elena-Bruyako approved these changes

2024-12-07 15:18 UTC, merged