implemented shoppingcart realisation
Oleksii-Melashchenko/Shop pull request #12
Opened 2024-12-14 11:08 UTC by Oleksii-Melashchenko

2024-12-15 12:28 UTC, Elena-Bruyako requested changes
see comments

2024-12-15 12:28 UTC, Elena-Bruyako commented on src/main/java/com/clozex/shop/model/ShoppingCart.java
> +    private Boolean isDeleted = false;
```suggestion
    private boolean isDeleted = false;
```

2024-12-15 12:28 UTC, Elena-Bruyako commented on src/main/java/com/clozex/shop/service/ShoppingCartService.java
> +
```suggestion
```

2024-12-15 12:28 UTC, Elena-Bruyako commented on src/main/java/com/clozex/shop/service/impl/BookServiceImpl.java
> +        cartItemRepository.deleteByBookId(id);
```suggestion
```

2024-12-15 12:28 UTC, Elena-Bruyako commented on src/main/java/com/clozex/shop/service/impl/BookServiceImpl.java
> +    @Transactional
```suggestion
```

2024-12-15 12:28 UTC, Elena-Bruyako commented on src/main/java/com/clozex/shop/service/impl/ShoppingCartServiceImpl.java
> +        cartItemRepository.save(cartItem);
you have cascade type all, so save shop cart instead of cartItem (check other places)

2024-12-15 12:28 UTC, Elena-Bruyako commented on src/main/java/com/clozex/shop/service/impl/ShoppingCartServiceImpl.java
> +        Book book = bookRepository.findById(request.bookId())
it's better to check it after `ShoppingCart shoppingCart = getShoppingCartOrCreate(user)`; in `addCartItem` method

2024-12-16 07:20 UTC, liliia-ponomarenko approved these changes
Good job!

2024-12-16 07:24 UTC, merged