added all logic
Oleksii-Melashchenko/Shop pull request #13
Opened 2024-12-23 23:19 UTC by Oleksii-Melashchenko

2024-12-24 15:09 UTC, JJJazl requested changes

2024-12-24 15:09 UTC, JJJazl commented on src/main/java/com/clozex/shop/repository/order/OrderRepository.java
> +
```suggestion
```

2024-12-24 15:09 UTC, JJJazl commented on src/main/java/com/clozex/shop/repository/order/OrderItemRepository.java
> +
```suggestion
```

2024-12-24 15:09 UTC, JJJazl commented on src/main/java/com/clozex/shop/repository/order/OrderItemRepository.java
> +
```suggestion
```

2024-12-24 15:09 UTC, JJJazl commented on src/main/java/com/clozex/shop/service/ShoppingCartService.java
> +
```suggestion
```

2024-12-24 15:09 UTC, JJJazl commented on src/main/java/com/clozex/shop/service/impl/OrderServiceImpl.java
> +public class OrderServiceImpl implements OrderService {
```suggestion
@Service
@RequiredArgsConstructor
@Transactional
public class OrderServiceImpl implements OrderService {
```

2024-12-24 15:09 UTC, JJJazl commented on src/main/java/com/clozex/shop/service/impl/OrderServiceImpl.java
> +    @Transactional
```suggestion
```

2024-12-24 15:09 UTC, JJJazl commented on src/main/java/com/clozex/shop/service/impl/OrderServiceImpl.java
> +        if (shoppingCart.getCartItems().isEmpty()) {
Lazy loading here. To avoid it you need to create a method in ShoppingCartRepository with `@Query` anotation and JOIN FETCH property (prefered way to do it) or with `@EntityGraph` anotation + informative method name, for example `findByUserIdFetchCartItems()`

2024-12-24 15:09 UTC, JJJazl commented on src/main/java/com/clozex/shop/service/impl/OrderServiceImpl.java
> +    }
I think it would be better to separate these methods in different endpoints and make each method simpler and easier to read/understand

2024-12-24 15:09 UTC, JJJazl commented on src/main/java/com/clozex/shop/service/impl/OrderServiceImpl.java
> +                .orElseThrow(() -> new EntityNotFoundException("Order not found"));
```suggestion
                .orElseThrow(() -> new EntityNotFoundException("Order not found by id: " + orderId));
```

2024-12-25 08:49 UTC, liliia-ponomarenko approved these changes
Good job! But let’s fix a few mistakes before merging ;)

2024-12-25 08:49 UTC, liliia-ponomarenko commented on src/main/java/com/clozex/shop/repository/order/OrderItemRepository.java
> +
```suggestion
```

2024-12-25 08:49 UTC, liliia-ponomarenko commented on src/main/java/com/clozex/shop/service/impl/OrderServiceImpl.java
> +                .anyMatch(authority -> authority.getAuthority().equals("ROLE_ADMIN"));
don't hardcode role use enum value

2024-12-25 08:49 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/changes/11-create-orders-table.yaml
> +            constraintName: fk_orders_user_id
add one empty line at the end of the file (check other files)

2024-12-25 09:40 UTC, merged